/*
 * lab_registry.c — 测试注册表：将每个外设的界面说明、按钮动作与后台运行函数对应起来。
 */
#include "lab.h"
#include "lab_game.h"
#include "lvgl.h"

/* 新测试：增加枚举、模块文件，然后在这里注册。 */
const unsigned lab_speaker_notes[8] = {262, 294, 330, 349, 392, 440, 494, 523};
/* 数组下标就是 lab_id_t；actions 的下标原样传给 run，新增按钮需保持两者对应。 */
const lab_module_t lab_modules[LAB_COUNT] = {
 [LAB_GAME] = {"Play Lab", "Pelican / bicycle ride", LV_SYMBOL_HOME, 0xFFD38A,
  "A seaside cycling game combining the IMU, display and touch. The starting grip becomes neutral immediately. Tilt forward/back to move up/down, left/right to steer. Collect fish, dodge cones, and keep your balance for 60 seconds. Center resets the neutral grip.",
  "LSM6DSL 104 Hz -> worker snapshots -> 30 Hz game\nInstant center / two-axis motion / heading / safe sensor restore",
  {"Pelican ride"}, lab_game_run},
 [LAB_RGB] = {"RGB light", "PA32 / PWM + DMA", LV_SYMBOL_EYE_OPEN, 0x86F5CA,
  "Watch the LED, not the screen. Cycle shows red, green and blue for one second each, then turns off. Confirm what you see.",
  "rt_device_find(\"rgbled\")\nrt_device_control(..., PWM_CMD_SET_COLOR, &color)\nUPDATE DMA sends the color bits.",
  {"Cycle RGB", "Red", "Blue", "Off"}, lab_rgb_run},
 [LAB_GPIO] = {"GPIO / motor", "PA20 / digital output", LV_SYMBOL_CHARGE, 0xFFC580,
  "PA20 drives the motor output. Pulse runs for 200 ms and always returns LOW. Confirm the physical response; pin readback alone is not a motor test.",
  "HAL_PIN_Set(PAD_PA20, GPIO_A20, ...)\nrt_pin_mode(20, PIN_MODE_OUTPUT)\nrt_pin_write(20, PIN_HIGH / PIN_LOW)",
  {"Pulse 200 ms", "Set LOW", NULL, NULL}, lab_gpio_run},
 [LAB_KEY] = {"Buttons", "KEY1 PA34 / KEY2 PA43", LV_SYMBOL_POWER, 0xC6A4FF,
  "Choose KEY1 or KEY2, then briefly press and release within 8 seconds. KEY1 is also the power key: do not hold it down. Its BSP pin configuration is preserved.",
  "rt_pin_mode(43, PIN_MODE_INPUT)\nrt_pin_read(43) / rt_pin_read(34)\n20 ms polling + debounce; no work in IRQ.",
  {"KEY2", "KEY1", NULL, NULL}, lab_key_run},
 [LAB_ADC] = {"Battery ADC", "bat1 / channel 7", LV_SYMBOL_BATTERY_3, 0xFFE38B,
  "Read the internal battery channel. This verifies acquisition, not battery health or calibration. Continuous updates until Stop or leaving. PA34 remains a key input.",
  "rt_adc_enable(adc, 7)\nrt_device_control(adc, RT_ADC_CMD_READ, &arg)\nrt_adc_disable(adc, 7)",
  {"Read battery", "Continuous", NULL, NULL}, lab_adc_run},
 [LAB_UART] = {"UART", "TX / RX / loopback", LV_SYMBOL_LOOP, 0x80CCFF,
  "115200 8N1. TX: check 3 LAB-TX frames on a terminal. RX: send LAB-RX + LF within 8 s. Loopback: jumper PA19 TX to PA18 RX, disconnect external TX first. UART1 console shares these pins and resumes after the test.",
  "rt_device_open(uart, ... | RT_DEVICE_FLAG_INT_RX)\nrt_device_write(...) / rt_device_read(...)\nAlways bound reads by remaining space.",
  {"Test TX", "Test RX", "Loopback", NULL}, lab_uart_run},
 [LAB_CHARGER] = {"Charger / I2C", "AW32001 / I2C2", LV_SYMBOL_USB, 0xFFABAB,
  "Read the charger ID and raw status registers. Charge-current settings are not changed. A successful read verifies the bus, not charging performance.",
  "rt_i2c_bus_device_find(\"i2c2\")\nrt_i2c_mem_read(bus, addr, reg, 8, data, len)\nRegister address + repeated-start read.",
  {"Read registers", NULL, NULL, NULL}, lab_charger_run},
 [LAB_IMU] = {"6-axis IMU", "LSM6DSL / accel + gyro", LV_SYMBOL_SHUFFLE, 0xA4BAFF,
  "Tilt the board and sample again. WHO_AM_I must match; acceleration in g, angular speed in deg/s and raw axes are shown. Continuous repeats until Stop or leaving. Sampling settings are restored after each read.",
  "rt_i2c_mem_read(...)\nWHO_AM_I -> enable 104 Hz -> data ready\nRead 12 bytes; decode signed 16-bit axes.",
  {"Sample axes", "Continuous", NULL, NULL}, lab_imu_run},
 [LAB_LIGHT] = {"Light sensor", "LTR303 / ambient light", LV_SYMBOL_IMAGE, 0xF8D08B,
  "Cover or illuminate the sensor and sample again. Display estimated lux plus CH0/CH1 raw counts, using actual gain and integration time. Continuous repeats until Stop or leaving. Control settings are restored after each read.",
  "Read manufacturer + part ID\nEnable ALS -> poll data-ready\nrt_i2c_mem_read(...): read both channels.",
  {"Read light", "Continuous", NULL, NULL}, lab_light_run},
 [LAB_MAG] = {"3-axis magnet", "MMC5603 / X Y Z", LV_SYMBOL_GPS, 0x94DDD6,
  "Move a magnet near the board, then sample again. Display uT and signed raw counts, without offset/compass calibration. Continuous repeats until Stop or leaving.",
  "Read product ID (0x39)\nTrigger one-shot -> poll status\nDecode three 20-bit samples.",
  {"Read field", "Continuous", NULL, NULL}, lab_mag_run},
 [LAB_RTC] = {"Real-time clock", "RTC / timekeeping", LV_SYMBOL_REFRESH, 0xB8C8F4,
  "Read twice across 1.2 seconds and check that time advances. This does not set the clock; an unset calendar can still tick correctly.",
  "rt_device_find(\"rtc\")\nrt_device_control(rtc, RT_DEVICE_CTRL_RTC_GET_TIME, &t)\nCompare two samples.",
  {"Check ticking", NULL, NULL, NULL}, lab_rtc_run},
 [LAB_DISPLAY] = {"Display", "CO5300 / 390 x 450", LV_SYMBOL_VIDEO, 0xFFAFD0,
  "Open full-screen patterns. Tap to cycle red, green, blue, white and black. Look for dead pixels and uneven areas, then confirm.",
  "lv_obj_set_style_bg_color(...)\nlv_obj_invalidate(...)\nThe SDK LCD flush driver transfers pixels.",
  {"Open patterns", NULL, NULL, NULL}, NULL},
 [LAB_TOUCH] = {"Touch panel", "Single / two fingers", LV_SYMBOL_OK, 0x80DCCF,
  "Single: tap four targets; the active target and coordinates are shown. Two fingers: hold two contacts together for 250 ms, then move them. The diagnostic shows actual reported count; two-point support depends on the panel firmware. Done or an edge swipe exits.",
  "lv_indev_get_point(...) for single touch\nObserve SDK FT6146 frames via --wrap\nDecode real contact IDs; no second reader.",
  {"Single point", "Two fingers", NULL, NULL}, lab_touch_run},
 [LAB_MIC] = {"Microphone", "On-chip codec / mono", LV_SYMBOL_AUDIO, 0xC6A4FF,
  "Record 3 seconds while speaking or clapping. Watch dBFS and raw PCM levels, then compare original and +18 dB playback. Boost also amplifies noise; it does not change mic sensitivity. dBFS is a digital level, not sound-pressure dB SPL. Recording stays in RAM.",
  "audio_open2(..., AUDIO_RX, ...)\nPCM arrives in as_callback_cmd_data_coming\naudio_close(...) before playback.",
  {"Record 3 s", "Play original", "Play +18 dB", NULL}, lab_mic_run},
 [LAB_SPEAKER] = {"Speaker", "Codec / PA42 amplifier", LV_SYMBOL_VOLUME_MAX, 0xFFC580,
  "Connect a speaker to the board speaker socket. Choose one of eight notes: C4 to C5 (one octave). Set volume (0 is mute) and frequency, then Play custom, or choose a note. Each plays for 2 seconds. Play WAV plays a built-in PCM melody at the selected volume; frequency only affects custom tones. Controls apply before playback. Confirm the sound is audible and clear. STOP TEST closes playback.",
  "audio_open2(..., AUDIO_TX, ...)\naudio_write(...): handle backpressure\naudio_close(...); restore volume.",
  {"Do C4 / 262 Hz", "Re D4 / 294 Hz", "Mi E4 / 330 Hz", "Fa F4 / 349 Hz", "Sol G4 / 392 Hz", "La A4 / 440 Hz", "Si B4 / 494 Hz", "Do C5 / 523 Hz", "Play custom", "Play WAV"}, lab_speaker_run},
 [LAB_BLE] = {"Bluetooth", "BLE scan / link / data", LV_SYMBOL_BLUETOOTH, 0x80CCFF,
  "Open BLE tests. Use a phone BLE tool to connect, subscribe TX and write RX. STOP or Back closes radio activities; bonds remain.",
  "BLE callbacks -> event queue -> dedicated task\nLVGL reads snapshots; no UI calls in callbacks.",
  {"Open BLE tests"}, NULL},
 [LAB_PAN] = {"Bluetooth Internet", "BTPAN / HTTP / MQTT", LV_SYMBOL_WIFI, 0x86F5CA,
 "Enable phone Bluetooth tethering / iPhone Personal Hotspot, then pair from phone Settings. Test PAN, IP, DNS, HTTP and MQTT loopback. STOP or Back disconnects; bonds remain. HID phone links have been tested on Android and iPhone.",
 "bt_interface_conn_ext(..., BT_PROFILE_PAN)\nDHCP -> DNS -> nonblocking TCP -> HTTP HEAD",
 {"Open PAN tests"}, NULL}
};
