#!/usr/bin/env python3
"""Generate flash-resident game PCM; --check verifies the committed asset."""
import argparse
import math
from pathlib import Path

RATE = 16000
HEAD = 640
TAIL = 960
SCORES = {
    'fish': [(880, 880, 80), (1320, 1320, 80)],
    'heal': [(660, 660, 80), (880, 880, 80), (1320, 1320, 80)],
    'hit': [(1046, 622, 150)],
    'start': [(523, 523, 80), (784, 784, 80)],
    'win': [(659, 659, 120), (880, 880, 120), (1047, 1047, 140), (1319, 1319, 300)],
    'lose': [(784, 784, 150), (659, 659, 150), (523, 523, 300)],
}


def samples(notes):
    pcm = [0] * HEAD
    for hz, end_hz, ms in notes:
        slot = ms * 16
        voiced = slot - 160
        for pos in range(voiced):
            envelope = min(1, pos / 192, (voiced - 1 - pos) / 480)
            envelope = .5 - .5 * math.cos(math.pi * envelope)
            seconds = pos / RATE
            phase = math.tau * (hz * seconds + (end_hz - hz) * seconds**2 / (2 * voiced / RATE))
            wave = .82 * math.sin(phase) + .13 * math.sin(2 * phase) + .05 * math.sin(3 * phase)
            pcm.append(int(3000 * envelope * wave))
        pcm.extend([0] * 160)
    return pcm + [0] * TAIL


def render():
    lines = ['/* Generated by tools/generate_game_audio.py; do not edit. */',
             '#ifndef LAB_GAME_PCM_H', '#define LAB_GAME_PCM_H', '#include <stdint.h>',
             '#include "lab_game_sound.h"', f'#define SOUND_SAMPLE_RATE {RATE}',
             f'#define SOUND_HEAD {HEAD}', f'#define SOUND_TAIL {TAIL}']
    for name, notes in SCORES.items():
        pcm = samples(notes)
        lines.append(f'static const int16_t pcm_{name}[] = {{')
        for i in range(0, len(pcm), 16):
            lines.append('    ' + ','.join(map(str, pcm[i:i+16])) + ',')
        lines.append('};')
    lines += ['typedef struct { const int16_t *data; unsigned count; } game_pcm_t;',
              'static const game_pcm_t game_pcm[] = {', '    {0,0},']
    for name in SCORES:
        lines.append(f'    [GAME_SOUND_{name.upper()}] = {{pcm_{name},sizeof(pcm_{name})/sizeof(pcm_{name}[0])}},')
    return '\n'.join(lines + ['};', '#endif', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'src/lab_game_pcm.h'
    output = render()
    if args.check:
        if not target.exists() or target.read_text() != output:
            raise SystemExit('Game PCM is stale: run tools/generate_game_audio.py')
        print('PASS: game PCM matches the offline score generator.')
    else:
        target.write_text(output)
        print(f'Generated {target}: {sum(len(samples(n))*2 for n in SCORES.values())} PCM bytes')
