#!/usr/bin/env python3
"""生成原创两秒提示旋律及固件资源；替换 WAV 后可用 --input 重新嵌入。"""
import argparse
import math
from pathlib import Path
import struct
import wave
root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--input', type=Path)
args = parser.parse_args()
path = root / 'assets/speaker.wav'
if args.input:
    data = args.input.read_bytes()
else:
    samples = []
    for freq in (523.25, 659.25, 783.99, 1046.50):
        for i in range(8000):
            t = i / 16000
            envelope = min(i / 160, (7999 - i) / 400, 1) * math.exp(-3 * t)
            value = math.sin(2 * math.pi * freq * t) + .2 * math.sin(4 * math.pi * freq * t)
            samples.append(int(7000 * envelope * value))
    with wave.open(str(path), 'wb') as wav:
        wav.setparams((1, 2, 16000, 0, 'NONE', 'not compressed'))
        wav.writeframes(struct.pack('<%dh' % len(samples), *samples))
    data = path.read_bytes()
with wave.open(__import__('io').BytesIO(data), 'rb') as wav:
    if (wav.getnchannels(), wav.getsampwidth(), wav.getframerate(), wav.getcomptype()) != (1, 2, 16000, 'NONE'):
        raise SystemExit('Expected PCM WAV: mono, 16-bit, 16000 Hz')
    if not wav.getnframes():
        raise SystemExit('WAV must contain samples')
path.write_bytes(data)
inc = root / 'src/lab_wav_sample.inc'
inc.write_text('/* Generated by tools/generate_wav.py; PCM WAV bytes. */\n' + '\n'.join(
    ','.join('0x%02x' % b for b in data[i:i+16]) + ',' for i in range(0, len(data), 16)) + '\n')
print(f'Embedded {len(data)} bytes from {path}')
